apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2-waitforfirstconsumer
  resources:
    requests:
      storage: 60Gi